[[blueprint]]
[blueprint.main]
class = "web.main"

[[websocket]]
[websocket.WSHandler]
class = "web.main.websocket"
path = "/websocket"

[config.login_manager]
enable = false
session_protection = "strong"
login_view = "main.login"

[config.csrf]
enable = false
