blueprint:
  - main:
      class: web.main
websocket:
  - WSHandler:
      class: web.main.websocket
      path: /websocket
config:
  login_manager:
    enable: false
    session_protection: strong
    login_view: main.login
  csrf:
    enable: false